### PR TITLE
sysutils/R-cran-fs:1.5.0

### PR DESCRIPTION
**Pull request by yzgyyang**
```
new port: sysutils/R-cran-fs: Cross-Platform File System Operations

Approved by: lwhsu
```

### CODE REVIEW

**Comment by lwhsu** [comment]
> `new port: sysutils/R-cran-fs: Cross-Platform File System Operations Based on 'libuv'`

this line exceeds 80 characters, and it's preferred to keep in 72 characters.

**Review by lwhsu — APPROVED** [review]

**Comment by yzgyyang** [comment]
> > `new port: sysutils/R-cran-fs: Cross-Platform File System Operations Based on 'libuv'`
> 
> this line exceeds 80 characters, and it's preferred to keep in 72 characters.

Noted, and change as required. Do we need to also limit this in `COMMENT` in `Makefile`?

**Comment by lwhsu** [comment]
> Noted, and change as required. Do we need to also limit this in `COMMENT` in `Makefile`?

I'm not 100% sure, but it's good to keep them not too line. I haven't checked this part in porter's handbook and portlint(1) suggests 70 characters.

(note that portlint(1) is just giving suggestions)

**Comment by yzgyyang** [comment]
> > Noted, and change as required. Do we need to also limit this in `COMMENT` in `Makefile`?
> 
> I'm not 100% sure, but it's good to keep them not too line. I haven't checked this part in porter's handbook and portlint(1) suggests 70 characters.
> 
> (note that portlint(1) is just giving suggestions)

Thanks! In this case, I will keep it as-is, since it best describes the port.

**Comment by lwhsu** [comment]
> Thanks! In this case, I will keep it as-is, since it best describes the port.

I'm fine with this, but please help me check if this is documented in porter's handbook.

**Comment by yzgyyang** [comment]
> > Thanks! In this case, I will keep it as-is, since it best describes the port.
> 
> I'm fine with this, but please help me check if this is documented in porter's handbook.

Ah... Actually there is a 70-character limit, though it is not strictly enforced to my knowledge. I will tweak all these patches to meet the requirement though.

Source: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/makefile-comment.html

**Pull request merged**
