### PR TITLE
devel/pecl-runkit7:4.0.0a2

### PR DESCRIPTION
**Pull request by yzgyyang**
new port: devel/pecl-runkit7: Extension to replace, rename, and remove user functions and classes

PR: 251867
Submitted by: Vikash Badal <vikashb@where-ever.za.net>
Approved by: lwhsu

### CODE REVIEW

**Review by lwhsu — APPROVED** [review]

**Comment by lwhsu** [comment]
It would be nice if you can also write the proposed commit message.

**Comment by yzgyyang** [comment]
> It would be nice if you can also write the proposed commit message.

Updated the message as the first comment, and will continue to do so.

BTW, is his "Documentation" line below "WWW" in `pkg-descr` acceptable?

**Comment by lwhsu** [comment]
> > It would be nice if you can also write the proposed commit message.
> 
> Updated the message as the first comment, and will continue to do so.
That's great!

> BTW, is his "Documentation" line below "WWW" in `pkg-descr` acceptable?

I don't remember there is such policy, but it is safer to keep WWW as the last line.

**Comment by yzgyyang** [comment]
> I don't remember there is such policy, but it is safer to keep WWW as the last line.

Will remove it then.

**Comment by lwhsu** [comment]
> > I don't remember there is such policy, but it is safer to keep WWW as the last line.
> 
> Will remove it then.

Or moving to upper is also fine.

**Comment by yzgyyang** [comment]
> > > I don't remember there is such policy, but it is safer to keep WWW as the last line.
> > 
> > 
> > Will remove it then.
> 
> Or moving to upper is also fine.

OK!

**Pull request merged**
